
ALTER TABLE public.onboarding_data
  ADD COLUMN IF NOT EXISTS physically_handicapped BOOLEAN DEFAULT false,
  ADD COLUMN IF NOT EXISTS headache_type TEXT,
  ADD COLUMN IF NOT EXISTS body_pain_location TEXT[] DEFAULT '{}',
  ADD COLUMN IF NOT EXISTS chest_pain_side TEXT,
  ADD COLUMN IF NOT EXISTS chest_pressure BOOLEAN DEFAULT false,
  ADD COLUMN IF NOT EXISTS stroke_history BOOLEAN DEFAULT false,
  ADD COLUMN IF NOT EXISTS cardiac_arrest_history BOOLEAN DEFAULT false,
  ADD COLUMN IF NOT EXISTS has_bp BOOLEAN DEFAULT false,
  ADD COLUMN IF NOT EXISTS bp_values TEXT,
  ADD COLUMN IF NOT EXISTS has_sugar BOOLEAN DEFAULT false,
  ADD COLUMN IF NOT EXISTS sugar_values TEXT,
  ADD COLUMN IF NOT EXISTS low_energy BOOLEAN DEFAULT false,
  ADD COLUMN IF NOT EXISTS proper_sleep BOOLEAN DEFAULT true,
  ADD COLUMN IF NOT EXISTS has_blood_report BOOLEAN DEFAULT false,
  ADD COLUMN IF NOT EXISTS pain_severity TEXT,
  ADD COLUMN IF NOT EXISTS pain_locations TEXT[] DEFAULT '{}',
  ADD COLUMN IF NOT EXISTS wound_scar_marks BOOLEAN DEFAULT false,
  ADD COLUMN IF NOT EXISTS wound_details TEXT,
  ADD COLUMN IF NOT EXISTS fractures BOOLEAN DEFAULT false,
  ADD COLUMN IF NOT EXISTS fracture_details TEXT,
  ADD COLUMN IF NOT EXISTS menstrual_flow TEXT,
  ADD COLUMN IF NOT EXISTS cycle_duration TEXT,
  ADD COLUMN IF NOT EXISTS pads_per_day INTEGER,
  ADD COLUMN IF NOT EXISTS menstrual_other_symptoms TEXT,
  ADD COLUMN IF NOT EXISTS menopausal BOOLEAN DEFAULT false,
  ADD COLUMN IF NOT EXISTS past_traumatic_history TEXT,
  ADD COLUMN IF NOT EXISTS surgical_history TEXT,
  ADD COLUMN IF NOT EXISTS medications_history TEXT,
  ADD COLUMN IF NOT EXISTS physical_exhaustion BOOLEAN DEFAULT false,
  ADD COLUMN IF NOT EXISTS smoking_duration TEXT,
  ADD COLUMN IF NOT EXISTS smoking_frequency TEXT,
  ADD COLUMN IF NOT EXISTS alcohol_duration TEXT,
  ADD COLUMN IF NOT EXISTS alcohol_frequency TEXT,
  ADD COLUMN IF NOT EXISTS other_addictions TEXT,
  ADD COLUMN IF NOT EXISTS ent_issues TEXT[] DEFAULT '{}',
  ADD COLUMN IF NOT EXISTS ocular_issues TEXT[] DEFAULT '{}',
  ADD COLUMN IF NOT EXISTS ocular_family_history BOOLEAN DEFAULT false,
  ADD COLUMN IF NOT EXISTS common_symptoms TEXT[] DEFAULT '{}',
  ADD COLUMN IF NOT EXISTS sexually_active BOOLEAN,
  ADD COLUMN IF NOT EXISTS blood_investigations TEXT[] DEFAULT '{}',
  ADD COLUMN IF NOT EXISTS imaging_done TEXT[] DEFAULT '{}',
  ADD COLUMN IF NOT EXISTS diet_type TEXT,
  ADD COLUMN IF NOT EXISTS meals_per_day INTEGER,
  ADD COLUMN IF NOT EXISTS food_type TEXT,
  ADD COLUMN IF NOT EXISTS outside_food_intake TEXT;
